// Master due-diligence checklist — 13 categories, 132 items.
// Fixed list (matches Otima's DD master). Each item is tracked per-deal with
// status/priority/owner/dates/risk/comments, stored in the deal's saved state.

export const DD_CATEGORIES = [
  {
    key: 'corporate',
    label: 'Corporate',
    items: [
      'Entity organizational documents',
      'Good Standing Certificates',
      'Authority to Sell',
      'Cap Table',
      'Litigation',
      'Material Contracts',
      'UCC Search',
      'OFAC/KYC',
      'Beneficial Ownership',
      'Tax IDs',
    ],
  },
  {
    key: 'titleSurvey',
    label: 'Title & Survey',
    items: [
      'ALTA Title Commitment',
      'Title Exceptions',
      'Pro Forma Policy',
      'ALTA Survey',
      'Access Easements',
      'Utility Easements',
      'Encroachments',
      "CCR's",
      'Mineral Rights',
      'Boundary Issues',
      'Mechanic Liens',
      'Tax Liens',
    ],
  },
  {
    key: 'legal',
    label: 'Legal',
    items: [
      'Purchase Agreement',
      'Amendments',
      'Disclosure Schedules',
      'Assignment Agreements',
      'Escrow Agreement',
      'Broker Agreements',
      'Representations & Warranties',
      'Indemnities',
      'Closing Deliverables',
      'Opinion Letters',
    ],
  },
  {
    key: 'financial',
    label: 'Financial',
    items: [
      '5 Years Financial Statements',
      'TTM Financials',
      'Monthly Financials',
      'General Ledger',
      'Trial Balance',
      'Bank Statements',
      'Tax Returns',
      'AR Aging',
      'AP Aging',
      'CapEx History',
      'Budget',
      'Forecast',
    ],
  },
  {
    key: 'operations',
    label: 'Operations',
    items: [
      'Organization Chart',
      'Payroll',
      'Vendor Contracts',
      'Management Agreements',
      'Utility Contracts',
      'Maintenance Logs',
      'SOPs',
      'IT Systems',
      'Cybersecurity',
      'Business Continuity',
    ],
  },
  {
    key: 'realEstate',
    label: 'Real Estate',
    items: [
      'Rent Roll',
      'Lease Abstracts',
      'Tenant Estoppels',
      'SNDA',
      'Security Deposits',
      'CAM Reconciliations',
      'Occupancy',
      'Vacancy',
      'Property Management Agreement',
      'Parking Inventory',
    ],
  },
  {
    key: 'engineering',
    label: 'Engineering',
    items: [
      'Property Condition Assessment',
      'Structural Report',
      'Roof Report',
      'HVAC Report',
      'Electrical Report',
      'Plumbing Report',
      'Fire Life Safety',
      'Elevator Inspection',
      'ADA Assessment',
      'Deferred Maintenance',
    ],
  },
  {
    key: 'environmental',
    label: 'Environmental',
    items: [
      'Phase I ESA',
      'Phase II ESA',
      'Asbestos',
      'Lead Paint',
      'Mold',
      'Radon',
      'Wetlands',
      'Flood Study',
      'Hazmat',
      'Environmental Permits',
    ],
  },
  {
    key: 'insurance',
    label: 'Insurance',
    items: [
      'Current Policies',
      'Loss Runs',
      'Claims History',
      'Property',
      'General Liability',
      'Umbrella',
      'Flood',
      'Builder Risk',
      'Cyber',
      'D&O',
    ],
  },
  {
    key: 'tax',
    label: 'Tax',
    items: [
      'Property Tax Bills',
      'Assessment Appeals',
      'Sales Tax',
      'Income Tax',
      'Transfer Tax',
      'Tax Nexus',
      'Deferred Taxes',
      'Tax Incentives',
    ],
  },
  {
    key: 'compliance',
    label: 'Compliance',
    items: [
      'Zoning',
      'Certificates of Occupancy',
      'Building Permits',
      'Fire Inspection',
      'OSHA',
      'EPA',
      'ADA',
      'Code Violations',
      'Licenses',
      'Regulatory Reviews',
    ],
  },
  {
    key: 'lender',
    label: 'Lender',
    items: [
      'Appraisal',
      'Debt Term Sheet',
      'Commitment Letter',
      'Loan Agreement',
      'Debt Covenants',
      'DSCR',
      'Insurance Requirements',
      'Legal Opinions',
      'Entity Docs',
      'Closing Checklist',
    ],
  },
  {
    key: 'closing',
    label: 'Closing',
    items: [
      'Settlement Statement',
      'Wire Instructions',
      'Deed',
      'Bill of Sale',
      'Assignment of Leases',
      'Assignment of Contracts',
      'Tenant Notices',
      'Keys',
      'Warranty Transfer',
      'Post Close Deliverables',
    ],
  },
];

export const DD_STATUSES = ['Not Started', 'Requested', 'Received', 'Reviewed', 'Complete'];
export const DD_PRIORITIES = ['High', 'Medium', 'Low'];
export const DD_RISKS = ['None', 'Low', 'Medium', 'High'];

// A stable id for an item: "<categoryKey>:<itemIndex>"
export function ddItemId(catKey, idx) {
  return `${catKey}:${idx}`;
}
